'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import WorldMap,{MapNews} from './components/WorldMap';
import WorldStats from './components/WorldStats';
import Timeline from './components/Timeline';
type News=MapNews&{time:string;source:string;url:string};
type Lang='es'|'en';
const categories=['Todos','Política','Seguridad','Economía','Ciencia','Tecnología','Desastres','General'];
const labels={es:{search:'Buscar país, ciudad o acontecimiento...',latest:'Últimos acontecimientos',news:'Noticias',live:'EN VIVO',updating:'ACTUALIZANDO',fallback:'No se pudo actualizar la fuente. Mostrando respaldo.',all:'Todos',read:'Leer fuente original →',geo:'Noticias geolocalizadas · actualización automática',loading:'Cargando noticias mundiales...',empty:'No hay noticias para este filtro.',events:'acontecimientos visibles',timeline:'LÍNEA TEMPORAL'},en:{search:'Search country, city or event...',latest:'Latest events',news:'News',live:'LIVE',updating:'UPDATING',fallback:'Could not update the source. Showing backup.',all:'All',read:'Read original source →',geo:'Geolocated news · automatic updates',loading:'Loading world news...',empty:'No news for this filter.',events:'visible events',timeline:'TIMELINE'}};
const cat={es:['Todos','Política','Seguridad','Economía','Ciencia','Tecnología','Desastres','General'],en:['All','Politics','Security','Economy','Science','Technology','Disasters','General']};
export default function Home(){
 const [lang,setLang]=useState<Lang>('es'),[news,setNews]=useState<News[]>([]),[selected,setSelected]=useState<string>(''),[filter,setFilter]=useState('Todos'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(false),[country,setCountry]=useState('Todos'),[timeNews,setTimeNews]=useState<News[]>([]);
 const t=labels[lang], categoriesUi=cat[lang];
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/news',{cache:'no-store'});const d=await r.json();const a=d.articles??[];setNews(a);setTimeNews(a);setError(Boolean(d.error));}catch{setError(true)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,900000);return()=>clearInterval(id)},[load]);
 const countries=useMemo(()=>Array.from(new Set(news.map(n=>n.country))).sort(),[news]);
 const activeCategory=lang==='en'?(cat.en.indexOf(filter)>=0?filter:filter==='Todos'?'All':filter):filter;
 const filtered=useMemo(()=>timeNews.filter(n=>(filter==='Todos'||n.category===filter)&&(country==='Todos'||n.country===country)&&(`${n.title} ${n.country}`.toLowerCase().includes(query.toLowerCase()))),[timeNews,filter,country,query]);
 const selectedNews=news.find(n=>n.id===selected)||filtered[0];
 const selectCountry=(c:string)=>{setCountry(c);setSelected('');};
 return <main className="app"><header className="topbar"><div className="brand">🌎 <span>WorldNews</span>Map</div><input className="search" placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/><button className="lang" onClick={()=>setLang(lang==='es'?'en':'es')}>{lang==='es'?'🇺🇸 EN':'🇪🇸 ES'}</button><button className="refresh" onClick={load}>↻</button></header><section className="content"><aside className="sidebar"><div className="section-title"><h2>{country==='Todos'?t.latest:`${t.news}: ${country}`}</h2><span className="badge">{loading?t.updating:t.live}</span></div>{error&&<div className="notice">{t.fallback}</div>}<WorldStats news={timeNews}/><Timeline news={news} onChange={setTimeNews}/><select className="country-select" value={country} onChange={e=>selectCountry(e.target.value)}><option value="Todos">{t.all}</option>{countries.map(c=><option key={c}>{c}</option>)}</select><div className="filters">{categoriesUi.map((c,i)=><button key={c} className={`filter ${activeCategory===c?'active':''}`} onClick={()=>setFilter(categories[i])}>{c}</button>)}</div>{country!=='Todos'&&<div className="country-stats"><strong>{filtered.length}</strong> {t.events}</div>}{filtered.length?filtered.map(n=><article key={n.id} className="news-card" onClick={()=>setSelected(n.id)}><div className="meta">{n.country} · {n.time}</div><div className="news-title">{n.title}</div><span className="category">{lang==='en'?(cat.en[categories.indexOf(n.category)]||n.category):n.category}</span></article>):<div className="empty">{loading?t.loading:t.empty}</div>}</aside><div className="map-wrap"><WorldMap news={filtered} onSelect={setSelected}/><div className="map-label">🛰️ {t.geo}</div>{selectedNews&&<div className="selected-news"><div className="meta">{selectedNews.country} · {selectedNews.time} · {selectedNews.source}</div><div className="selected-title">{selectedNews.title}</div><span className="category">{lang==='en'?(cat.en[categories.indexOf(selectedNews.category)]||selectedNews.category):selectedNews.category}</span><a className="source-link" href={selectedNews.url} target="_blank" rel="noreferrer">{t.read}</a></div>}<div className="legend"><div><i className="dot red"/>Seguridad / Security</div><div><i className="dot blue"/>Política / Politics</div><div><i className="dot green"/>Ciencia / Science</div><div><i className="dot yellow"/>Economía / Economy</div></div></div></section></main>;
}
