'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import WorldMap,{MapNews} from './components/WorldMap';
import WorldStats from './components/WorldStats';
type News=MapNews&{time:string;source:string;url:string};
const categories=['Todos','Política','Seguridad','Economía','Ciencia','Tecnología','Desastres','General'];
export default function Home(){
 const [news,setNews]=useState<News[]>([]),[selected,setSelected]=useState<string>(''),[filter,setFilter]=useState('Todos'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(false),[country,setCountry]=useState('Todos');
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/news',{cache:'no-store'});const d=await r.json();setNews(d.articles??[]);setError(Boolean(d.error));}catch{setError(true)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,900000);return()=>clearInterval(id)},[load]);
 const countries=useMemo(()=>Array.from(new Set(news.map(n=>n.country))).sort(),[news]);
 const filtered=useMemo(()=>news.filter(n=>(filter==='Todos'||n.category===filter)&&(country==='Todos'||n.country===country)&&(`${n.title} ${n.country}`.toLowerCase().includes(query.toLowerCase()))),[news,filter,country,query]);
 const selectedNews=news.find(n=>n.id===selected)||filtered[0];
 const selectCountry=(c:string)=>{setCountry(c);setSelected('');};
 return <main className="app"><header className="topbar"><div className="brand">🌎 <span>WorldNews</span>Map</div><input className="search" placeholder="Buscar país, ciudad o acontecimiento..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="refresh" onClick={load}>↻</button></header><section className="content"><aside className="sidebar"><div className="section-title"><h2>{country==='Todos'?'Últimos acontecimientos':`Noticias: ${country}`}</h2><span className="badge">{loading?'ACTUALIZANDO':'EN VIVO'}</span></div>{error&&<div className="notice">No se pudo actualizar la fuente. Mostrando respaldo.</div>}<WorldStats news={news}/><select className="country-select" value={country} onChange={e=>selectCountry(e.target.value)}><option>Todos</option>{countries.map(c=><option key={c}>{c}</option>)}</select><div className="filters">{categories.map(c=><button key={c} className={`filter ${filter===c?'active':''}`} onClick={()=>setFilter(c)}>{c}</button>)}</div>{country!=='Todos'&&<div className="country-stats"><strong>{filtered.length}</strong> acontecimientos visibles</div>}{filtered.length?filtered.map(n=><article key={n.id} className="news-card" onClick={()=>setSelected(n.id)}><div className="meta">{n.country} · {n.time}</div><div className="news-title">{n.title}</div><span className="category">{n.category}</span></article>):<div className="empty">{loading?'Cargando noticias mundiales...':'No hay noticias para este filtro.'}</div>}</aside><div className="map-wrap"><WorldMap news={filtered} onSelect={setSelected}/><div className="map-label">🛰️ Noticias geolocalizadas · actualización automática</div>{selectedNews&&<div className="selected-news"><div className="meta">{selectedNews.country} · {selectedNews.time} · {selectedNews.source}</div><div className="selected-title">{selectedNews.title}</div><span className="category">{selectedNews.category}</span><a className="source-link" href={selectedNews.url} target="_blank" rel="noreferrer">Leer fuente original →</a></div>}<div className="legend"><div><i className="dot red"/>Seguridad</div><div><i className="dot blue"/>Política / tecnología</div><div><i className="dot green"/>Ciencia</div><div><i className="dot yellow"/>Economía</div></div></div></section></main>;
}
