import {NextResponse} from 'next/server';
export const dynamic='force-dynamic';
type Article={id:string;title:string;country:string;category:string;time:string;lat:number;lng:number;url:string;source:string};
const FALLBACK:Article[]=[{id:'demo-1',title:'WorldNewsMap está listo para recibir noticias en tiempo real',country:'Mundo',category:'General',time:new Date().toISOString(),lat:20,lng:0,url:'https://www.gdeltproject.org/',source:'GDELT'}];
const PLACES:Array<[RegExp,string,number,number]>=[[/colombia|bogota|bogotá|barranquilla/i,'Colombia',4.57,-74.08],[/venezuela|caracas/i,'Venezuela',10.48,-66.90],[/ecuador|quito/i,'Ecuador',-0.18,-78.47],[/peru|lima/i,'Perú',-12.05,-77.04],[/brazil|brasil|sao paulo|são paulo|rio de janeiro/i,'Brasil',-14.24,-51.93],[/argentina|buenos aires/i,'Argentina',-34.60,-58.38],[/chile|santiago/i,'Chile',-33.45,-70.67],[/mexico|mexico city/i,'México',19.43,-99.13],[/united states|usa|u\.s\.|washington|new york|california/i,'Estados Unidos',38.90,-77.04],[/canada|ottawa|toronto/i,'Canadá',45.42,-75.70],[/ukraine|kyiv|kiev/i,'Ucrania',50.45,30.52],[/russia|moscow|moscú/i,'Rusia',55.76,37.62],[/israel|tel aviv|jerusalem|jerusalén/i,'Israel',31.77,35.21],[/gaza|palestine|palestina/i,'Palestina',31.50,34.47],[/iran|tehran|teheran/i,'Irán',35.69,51.39],[/china|beijing|peking|shanghai/i,'China',39.90,116.40],[/japan|tokyo/i,'Japón',35.68,139.69],[/india|delhi|mumbai/i,'India',28.61,77.21],[/australia|sydney|melbourne/i,'Australia',-33.87,151.21],[/south africa|cape town|johannesburg/i,'Sudáfrica',-33.92,18.42],[/egypt|cairo/i,'Egipto',30.04,31.24],[/nigeria|lagos|abuja/i,'Nigeria',9.08,7.40],[/kenya|nairobi/i,'Kenia',-1.29,36.82],[/germany|berlin/i,'Alemania',52.52,13.40],[/france|paris/i,'Francia',48.86,2.35],[/united kingdom|uk|london|londres/i,'Reino Unido',51.51,-0.13],[/italy|rome|roma/i,'Italia',41.90,12.50],[/spain|madrid/i,'España',40.42,-3.70]];
function locate(text:string){const hit=PLACES.find(p=>p[0].test(text));return hit?{country:hit[1],lat:hit[2],lng:hit[3]}:{country:'Mundo',lat:20,lng:0};}
function categoryOf(title:string){const t=title.toLowerCase();if(/war|conflict|attack|military|security|ukraine|israel|gaza|guerra|conflicto|ataque/.test(t))return'Seguridad';if(/election|president|government|minister|politic|parliament|elección|presidente|gobierno/.test(t))return'Política';if(/market|economy|economic|bank|trade|inflation|stock|economía|mercado/.test(t))return'Economía';if(/science|research|climate|space|health|medical|ciencia|investigación/.test(t))return'Ciencia';if(/technology|software|artificial intelligence|\bai\b|chip|tecnología/.test(t))return'Tecnología';if(/earthquake|flood|storm|hurricane|fire|volcano|terremoto|inundación|huracán|incendio/.test(t))return'Desastres';return'General';}
function clean(s:string){return s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
function tag(xml:string,tag:string){const m=xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`,'i'));return m?clean(m[1]):'';}
async function fetchRss(url:string,source:string):Promise<Article[]>{const r=await fetch(url,{cache:'no-store',headers:{accept:'application/rss+xml, application/xml, text/xml'}});if(!r.ok)throw new Error(`${source} ${r.status}`);const xml=await r.text();return [...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].slice(0,25).map((m,i)=>{const item=m[0],title=tag(item,'title'),link=tag(item,'link')||tag(item,'guid'),description=tag(item,'description'),date=tag(item,'pubDate')||tag(item,'published')||tag(item,'updated'),text=`${title} ${description}`,p=locate(text);return{id:`rss-${source}-${i}-${encodeURIComponent(link).slice(0,20)}`,title,country:p.country,category:categoryOf(title),time:new Date(date||Date.now()).toISOString(),lat:p.lat,lng:p.lng,url:link,source};}).filter(a=>a.title&&a.url);}
async function fetchGdelt(){const url='https://api.gdeltproject.org/api/v2/doc/doc?query=(news%20OR%20world)&mode=artlist&maxrecords=50&timespan=6h&sort=datedesc&format=json';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`GDELT ${r.status}`);const d=await r.json();return(d.articles??[]).map((a:any,i:number)=>{const title=String(a.title??''),p=locate(`${title} ${a.domain??''}`);return{id:`gdelt-${i}`,title,country:p.country,category:categoryOf(title),time:parseDate(a.seendate),lat:p.lat,lng:p.lng,url:String(a.url??''),source:String(a.domain||'GDELT')};}).filter((a:Article)=>a.url);}
function parseDate(v:any){const s=String(v??'');if(/^\d{14}$/.test(s)){return new Date(`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T${s.slice(8,10)}:${s.slice(10,12)}:${s.slice(12,14)}Z`).toISOString();}const d=new Date(s);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString();}
export async function GET(){
 const sources=[['BBC','https://feeds.bbci.co.uk/news/world/rss.xml'],['AlJazeera','https://www.aljazeera.com/xml/rss/all.xml'],['Guardian','https://www.theguardian.com/world/rss']];
 const results:Article[]=[];
 const settled=await Promise.allSettled(sources.map(([s,u])=>fetchRss(u,s)));
 for(const r of settled)if(r.status==='fulfilled')results.push(...r.value);
 if(!results.length){try{results.push(...await fetchGdelt())}catch(e){console.error('GDELT fallback failed',e)}}
 const unique=Array.from(new Map(results.map(a=>[a.url,a])).values()).sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime());
 return NextResponse.json({source:unique.length?'RSS/GDELT':'fallback',articles:unique.length?unique:FALLBACK,updatedAt:new Date().toISOString(),error:unique.length?undefined:'news_sources_unavailable'},{status:200,headers:{'Cache-Control':'s-maxage=600, stale-while-revalidate=300'}});
}
